"""empty message

Revision ID: 07197993bfad
Revises: 11f58f42e476
Create Date: 2021-10-22 19:34:01.049893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07197993bfad'
down_revision = '11f58f42e476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('address', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Artist', 'address')
    # ### end Alembic commands ###
