"""empty message

Revision ID: 42be1454b1aa
Revises: 893890605a72
Create Date: 2021-10-17 10:09:54.537949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42be1454b1aa'
down_revision = '893890605a72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('seeking_talent', sa.Boolean(), nullable=False))
    op.add_column('Venue', sa.Column('seeking_description', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'seeking_description')
    op.drop_column('Venue', 'seeking_talent')
    # ### end Alembic commands ###
