"""empty message

Revision ID: 4630e41a9d41
Revises: b92776d9c739
Create Date: 2021-09-18 22:14:10.527701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4630e41a9d41'
down_revision = 'b92776d9c739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Artist_show_id_fkey', 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'show_id')
    op.drop_constraint('Venue_show_id_fkey', 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'show_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Venue_show_id_fkey', 'Venue', 'Show', ['show_id'], ['id'])
    op.add_column('Artist', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Artist_show_id_fkey', 'Artist', 'Show', ['show_id'], ['id'])
    # ### end Alembic commands ###
