"""empty message

Revision ID: 64b6188baf87
Revises: 9e80351f169b
Create Date: 2021-10-22 19:48:40.641042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b6188baf87'
down_revision = '9e80351f169b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
