"""empty message

Revision ID: b92776d9c739
Revises: 08e76dd1e3c6
Create Date: 2021-09-18 22:00:16.097208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b92776d9c739'
down_revision = '08e76dd1e3c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('show_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'Show', ['show_id'], ['id'])
    op.add_column('Venue', sa.Column('show_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Venue', 'Show', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'show_id')
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'show_id')
    # ### end Alembic commands ###
